### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by dhaigit** [tyron12233/CodeAssist#177]
I got a couple of...

ERROR: WARNING: linker: ...libzipalign.so unused DT entry ...

...and a...

CANNOT LINK EXECUTABLE ...libzipalign.so: cannot locate symbol ... referenced by ...libzipalign.so

There's a generated.apk in ouput folder but it fails to install.

**Comment by tyron12233** [comment]
Its fixed on [this commit] and will be released with 0.2.5.1

**Comment by tyron12233** [comment]
Should be fixed on https://github.com/tyron12233/CodeAssist/releases/tag/ALPHA-0.2.5.1

**Comment by dhaigit** [comment]
I still get "compilation failed" error.

ERROR: Unable to find generated apk file.

It says that even though there is a generared.apk in output. Installation of apk still fails as before.

**Comment by tyron12233** [comment]
The apk file has been updated, please re-download it again.

**Comment by rexllc** [comment]
Same issue.

**Comment by dhaigit** [comment]
It's fine now.

**Comment by dhaigit** [comment]
"Fixed but not closed" means you would like for us to close it, or you would like for it to be kept open?

**Comment by tyron12233** [comment]
Fixed but not closed means the issue has been already fixed and is waiting for the author of the issue to confirm that it has been fixed.

**Comment by dhaigit** [comment]
I think it's fixed.
